
/* DATABASE INSERTS FOR GENERATE DATA*/

-- Insert Directors
INSERT INTO Directors (first_name, last_name, date_of_birth, overview, website) VALUES
('John', 'Smith', '1960-05-10', 'John Smith is known for his impactful storytelling in independent cinema.', 'http://www.johnsmithfilms.com'),
('Jane', 'Doe', '1972-03-22', 'Jane Doe has directed award-winning documentaries.', 'http://www.janedoedirector.com'),
('Michael', 'Johnson', '1985-11-15', 'Michael Johnson is a director of blockbuster action films.', 'http://www.mjfilms.com'),
('Emily', 'Davis', '1990-07-07', 'Emily Davis is a rising talent in the horror genre.', 'http://www.emilydavisfilms.com'),
('Robert', 'Lee', '1955-08-18', 'Robert Lee has been in the industry for over 30 years.', 'http://www.robertleeproductions.com'),
('Sarah', 'Wilson', '1980-09-01', 'Sarah Wilson specializes in historical drama films.', 'http://www.sarahwilsonfilms.com'),
('David', 'Brown', '1975-12-25', 'David Brown has worked extensively in TV and film.', 'http://www.davidbrowndirector.com'),
('Sophia', 'Garcia', '1989-03-13', 'Sophia Garcia brings a fresh perspective to romantic comedies.', 'http://www.sophiagarciafilms.com'),
('Chris', 'Martinez', '1991-10-30', 'Chris Martinez is known for groundbreaking sci-fi productions.', 'http://www.chrismartinezfilms.com'),
('Anna', 'Taylor', '1968-02-20', 'Anna Taylor has won multiple awards for her avant-garde films.', 'http://www.annataylorfilms.com'),
('James', 'Moore', '1979-05-05', 'James Moores work explores the complexity of human emotions.', 'http://www.jamesmooredirector.com'),
('Olivia', 'Harris', '1982-04-14', 'Olivia Harris is recognized for her feminist film narratives.', 'http://www.oliviaharrisfilms.com'),
('William', 'Clark', '1961-06-23', 'William Clark has directed several acclaimed war dramas.', 'http://www.williamclarkfilms.com'),
('Isabella', 'Martins', '1977-09-18', 'Isabella Martins has a diverse filmography, spanning genres.', 'http://www.isabellamartinsdirector.com'),
('Daniel', 'Rodriguez', '1988-11-01', 'Daniel Rodriguez has become a household name in animation.', 'http://www.danielrodriguezfilms.com'),
('Mia', 'Anderson', '1994-03-27', 'Mia Anderson is a young director specializing in short films.', 'http://www.miaandersonfilms.com'),
('Lucas', 'Thompson', '1965-12-17', 'Lucas Thompson is known for his suspense thrillers.', 'http://www.lucasthompsonfilms.com'),
('Charlotte', 'Martinez', '1984-08-07', 'Charlotte Martinezs work focuses on environmental issues.', 'http://www.charlottemartinezfilms.com'),
('Henry', 'King', '1950-01-11', 'Henry King is a veteran director with a career spanning five decades.', 'http://www.henrykingproductions.com'),
('Amelia', 'Scott', '1993-10-19', 'Amelia Scott is a passionate filmmaker creating films about social justice.', 'http://www.ameliascottfilms.com'),
('Elijah', 'Bennett', '1986-06-09', 'Elijah Bennetts films often explore futuristic societies.', 'http://www.elijahbennettfilms.com'),
('Grace', 'Green', '1970-02-25', 'Grace Green is celebrated for her deeply emotional dramas.', 'http://www.gracegreenfilms.com'),
('Alexander', 'Young', '1987-12-05', 'Alexander Young is a prominent figure in modern indie cinema.', 'http://www.alexanderyoungfilms.com'),
('Zoe', 'Walker', '1996-07-15', 'Zoe Walker is a director focused on LGBTQ+ stories.', 'http://www.zoewalkerfilms.com'),
('Sebastian', 'Perez', '1981-04-02', 'Sebastian Perez creates films that challenge social norms.', 'http://www.sebastianperezfilms.com'),
('Samantha', 'Evans', '1973-11-30', 'Samantha Evans films often revolve around strong female leads.', 'http://www.samanthaevansfilms.com'),
('Noah', 'Miller', '1992-09-21', 'Noah Millers documentaries shed light on untold historical stories.', 'http://www.noahmillerfilms.com'),
('Lily', 'Adams', '1983-06-03', 'Lily Adams work spans both film and theater direction.', 'http://www.lilyadamsfilms.com'),
('Ethan', 'Garcia', '1995-12-29', 'Ethan Garcia is an experimental filmmaker.', 'http://www.ethangarciafilms.com'),
('Ava', 'Mitchell', '1963-03-18', 'Ava Mitchell has directed some of the most iconic musicals in recent decades.', 'http://www.avamitchellfilms.com'),
('Matthew', 'Lopez', '1989-01-09', 'Matthew Lopez specializes in psychological thrillers.', 'http://www.matthewlopezfilms.com'),
('Chloe', 'Hill', '1974-08-26', 'Chloe Hill is known for her vibrant cinematography.', 'http://www.chloehillfilms.com'),
('Jack', 'Carter', '1971-05-19', 'Jack Carters work features surrealist elements.', 'http://www.jackcarterfilms.com'),
('Sophia', 'Russell', '1980-10-12', 'Sophia Russell focuses on family-centered narratives.', 'http://www.sophiarussellfilms.com'),
('Liam', 'Morgan', '1962-07-27', 'Liam Morgan has a strong background in international cinema.', 'http://www.liammorganfilms.com'),
('Mason', 'Cooper', '1990-04-30', 'Mason Cooper is a director with a passion for nature documentaries.', 'http://www.masoncooperfilms.com'),
('Isabella', 'Flores', '1986-11-24', 'Isabella Flores is a director in the Latinx film movement.', 'http://www.isabellafloresfilms.com'),
('Lucas', 'Reed', '1993-05-14', 'Lucas Reed is known for his innovative approach to character development.', 'http://www.lucasreedfilms.com'),
('Emily', 'Long', '1991-08-04', 'Emily Longs films often focus on themes of identity.', 'http://www.emilylongfilms.com'),
('William', 'Peterson', '1958-06-22', 'William Peterson has a background in military films.', 'http://www.williampetersonfilms.com'),
('Harper', 'Howard', '1990-11-17', 'Harper Howard is a director with a strong emphasis on LGBTQ+ representation.', 'http://www.harperhowardfilms.com'),
('Ethan', 'Reynolds', '1985-03-08', 'Ethan Reynolds work challenges traditional gender roles.', 'http://www.ethanreynoldsfilms.com'),
('Olivia', 'Simmons', '1989-06-13', 'Olivia Simmons is an emerging voice in the documentary field.', 'http://www.oliviasimmonsfilms.com'),
('Jackson', 'Fisher', '1978-02-05', 'Jackson Fisher specializes in neo-noir films.', 'http://www.jacksonfisherfilms.com'),
('Lily', 'Henderson', '1983-07-09', 'Lily Henderson has received acclaim for her period dramas.', 'http://www.lilyhendersonfilms.com'),
('Jacob', 'Murphy', '1994-09-29', 'Jacob Murphy is a director with an interest in animated feature films.', 'http://www.jacobmurphyfilms.com'),
('Sophia', 'Bell', '1992-11-22', 'Sophia Bell is a director focused on making impactful documentaries.', 'http://www.sophiabellfilms.com'),
('Daniel', 'Cruz', '1976-10-27', 'Daniel Cruz has worked on numerous international film collaborations.', 'http://www.danielcruzfilms.com'),
('Mia', 'Mitchell', '1987-05-11', 'Mia Mitchells work is known for its emotional depth.', 'http://www.miamitchellfilms.com');

-- Insert Writters
INSERT INTO Writter (first_name, last_name, date_of_birth, overview, website) VALUES
('John', 'Thompson', '1970-01-15', 'John Thompson is an accomplished author known for his historical novels.', 'http://www.johnthompsonwriter.com'),
('Emily', 'Jackson', '1983-03-22', 'Emily Jackson specializes in contemporary fiction that explores modern relationships.', 'http://www.emilyjacksonwrites.com'),
('Michael', 'Stewart', '1965-05-12', 'Michael Stewart has written several best-selling thrillers.', 'http://www.michaelstewartbooks.com'),
('Sarah', 'Parker', '1990-07-03', 'Sarah Parker is known for her impactful young adult novels.', 'http://www.sarahparkerwrites.com'),
('David', 'Smith', '1978-09-08', 'David Smith is a prolific science fiction writer.', 'http://www.davidsmithscifi.com'),
('Olivia', 'Morris', '1985-11-15', 'Olivia Morris writes psychological thrillers and mysteries.', 'http://www.oliviamorrisauthor.com'),
('James', 'White', '1960-12-20', 'James White has over 40 years of experience in writing literary fiction.', 'http://www.jameswhitefiction.com'),
('Sophia', 'Brown', '1975-06-18', 'Sophia Brown is an award-winning poet and novelist.', 'http://www.sophiabrownwrites.com'),
('Daniel', 'Harris', '1992-04-01', 'Daniel Harris has written numerous fantasy novels for young adults.', 'http://www.danielharrisfantasy.com'),
('Ava', 'Clark', '1988-10-27', 'Ava Clarks novels often explore themes of love, loss, and identity.', 'http://www.avaclarkauthor.com'),
('Liam', 'Wilson', '1971-02-09', 'Liam Wilson is a celebrated non-fiction writer.', 'http://www.liamwilsonwrites.com'),
('Isabella', 'Garcia', '1980-08-22', 'Isabella Garcia writes romance novels with strong female protagonists.', 'http://www.isabellagarciawrites.com'),
('William', 'Rodriguez', '1965-11-29', 'William Rodriguez is known for his action-packed detective novels.', 'http://www.williamrodriguezauthor.com'),
('Mia', 'Martinez', '1995-01-13', 'Mia Martinez is a rising star in the world of science fiction.', 'http://www.miamartinezwrites.com'),
('Noah', 'Lee', '1982-03-30', 'Noah Lee has written several popular graphic novels.', 'http://www.noahleewrites.com'),
('Emma', 'Davis', '1990-09-05', 'Emma Davis specializes in contemporary womens fiction.', 'http://www.emmadavisbooks.com'),
('Lucas', 'Perez', '1977-06-17', 'Lucas Perez has a strong background in crime fiction.', 'http://www.lucasperezwrites.com'),
('Amelia', 'Anderson', '1984-07-11', 'Amelia Anderson writes short stories and novellas focused on human nature.', 'http://www.ameliaandersonwrites.com'),
('Benjamin', 'Evans', '1986-05-06', 'Benjamin Evans is a novelist known for his dark, suspense-filled tales.', 'http://www.benjaminwritesevans.com'),
('Charlotte', 'Taylor', '1991-12-03', 'Charlotte Taylors novels highlight diverse voices in modern literature.', 'http://www.charlottetaylorwrites.com'),
('Elijah', 'Young', '1973-09-25', 'Elijah Young is an award-winning childrens book author.', 'http://www.elijahyoungwrites.com'),
('Harper', 'King', '1981-11-07', 'Harper King is an innovative fantasy and adventure novelist.', 'http://www.harperkingauthor.com'),
('Alexander', 'Wright', '1967-02-18', 'Alexander Wright has written extensively about historical events.', 'http://www.alexanderwrightwrites.com'),
('Grace', 'Hill', '1993-10-01', 'Grace Hill is a writer known for her engaging mystery novels.', 'http://www.gracehillwrites.com'),
('Henry', 'Walker', '1972-12-27', 'Henry Walker is a literary fiction author whose work often explores existential themes.', 'http://www.henrywalkerwrites.com'),
('Sophia', 'Baker', '1990-04-14', 'Sophia Baker is a novelist known for her romantic fiction.', 'http://www.sophiabakerwrites.com'),
('Jackson', 'Turner', '1968-05-23', 'Jackson Turner writes compelling novels that explore the human condition.', 'http://www.jacksonturnerwriter.com'),
('Olivia', 'Mitchell', '1985-07-19', 'Olivia Mitchell is a successful mystery writer with a global following.', 'http://www.oliviamitchellbooks.com'),
('Ethan', 'Campbell', '1992-08-08', 'Ethan Campbells work focuses on dystopian futures.', 'http://www.ethancampbellwrites.com'),
('Lily', 'Garcia', '1989-06-24', 'Lily Garcia is known for her powerful and moving poetry.', 'http://www.lilygarciaauthor.com'),
('Daniel', 'Clark', '1980-11-13', 'Daniel Clark writes psychological dramas with unexpected twists.', 'http://www.danielclarkwrites.com'),
('Emily', 'Perez', '1974-03-31', 'Emily Perez has written a series of fantasy books with strong female characters.', 'http://www.emilyperezwrites.com'),
('Lucas', 'Allen', '1965-01-09', 'Lucas Allen writes stories that blend science fiction with philosophy.', 'http://www.lucasallenwrites.com'),
('Charlotte', 'Scott', '1990-05-29', 'Charlotte Scott is a celebrated childrens book author.', 'http://www.charlottescottwrites.com'),
('James', 'Adams', '1987-02-20', 'James Adams writes fast-paced detective novels.', 'http://www.jamesadamswrites.com'),
('Amelia', 'Harris', '1983-09-14', 'Amelia Harris has written a number of powerful literary works.', 'http://www.ameliaharrisbooks.com'),
('Liam', 'Lopez', '1971-10-03', 'Liam Lopez is known for his horror stories.', 'http://www.liamlopezwrites.com'),
('Sophia', 'Nelson', '1985-06-30', 'Sophia Nelson writes science fiction novels with a focus on technology.', 'http://www.sophianelsonbooks.com'),
('Elijah', 'King', '1991-07-10', 'Elijah Kings novels often explore political intrigue and corruption.', 'http://www.elijahkingwrites.com'),
('Harper', 'Lee', '1982-03-12', 'Harper Lee has written several widely acclaimed fantasy novels.', 'http://www.harperleewrites.com'),
('Benjamin', 'Wright', '1975-11-02', 'Benjamin Wright writes memoirs that delve into personal and societal issues.', 'http://www.benjaminwrightauthor.com'),
('Grace', 'Rivera', '1989-01-19', 'Grace Riveras novels focus on the challenges and triumphs of immigrant families.', 'http://www.graceriverawrites.com'),
('Ethan', 'Evans', '1978-04-25', 'Ethan Evans writes science fiction with a focus on space exploration.', 'http://www.ethanevanswrites.com'),
('Mia', 'Sanders', '1987-09-08', 'Mia Sanders is a poet and essayist who writes about nature and spirituality.', 'http://www.miasanderswrites.com'),
('Daniel', 'Peterson', '1968-06-17', 'Daniel Peterson is an author with a passion for exploring the human psyche.', 'http://www.danielpetersonwrites.com'),
('Sophia', 'Thompson', '1990-11-26', 'Sophia Thompson writes historical romances set in the 19th century.', 'http://www.sophiathompsonbooks.com'),
('Lucas', 'Bailey', '1992-08-19', 'Lucas Bailey writes graphic novels with a focus on social issues.', 'http://www.lucasbaileywrites.com'),
('Grace', 'Martinez', '1983-05-04', 'Grace Martinez is a bilingual writer of novels and short stories.', 'http://www.gracemartinezbooks.com'),
('Jackson', 'Parker', '1995-12-12', 'Jackson Parker writes horror novels and short stories.', 'http://www.jacksonparkerwrites.com'),
('Lily', 'Robinson', '1979-07-15', 'Lily Robinson is an acclaimed novelist and essayist.', 'http://www.lilyrobinsonwrites.com'),
('Elijah', 'Brooks', '1984-10-06', 'Elijah Brooks writes speculative fiction with elements of the supernatural.', 'http://www.elijahbrookswrites.com')



-- Insert Genres
INSERT INTO Genres (genre_name) VALUES
('Action'), ('Comedy'), ('Drama'), ('Thriller'), ('Sci-Fi'), ('Horror'), ('Romance');

CREATE TABLE Actors (
    actor_id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    date_of_birth DATE NOT NULL,
    website VARCHAR(100) NOT NULL,
    actor_overview TEXT NOT NULL
);

INSERT INTO Actors (first_name, last_name, date_of_birth, website, actor_overview) VALUES
('John', 'Doe', '1985-05-15', 'http://www.johndoeactor.com', 'John Doe is a versatile actor known for his roles in both drama and action films.'),
('Emily', 'Smith', '1990-07-21', 'http://www.emilysmithactress.com', 'Emily Smith is a talented actress recognized for her performances in independent films.'),
('Michael', 'Johnson', '1983-03-11', 'http://www.michaeljohnsonactor.com', 'Michael Johnson is an award-winning actor with a background in theater and television.'),
('Sarah', 'Williams', '1979-11-02', 'http://www.sarahwilliamsactress.com', 'Sarah Williams has appeared in numerous romantic comedies and has a strong fan following.'),
('David', 'Brown', '1992-06-25', 'http://www.davidbrownactor.com', 'David Brown is a rising star known for his roles in action-packed blockbuster films.'),
('Sophia', 'Garcia', '1995-09-13', 'http://www.sophiagarciaactress.com', 'Sophia Garcia is a versatile actress with experience in both television series and films.'),
('Daniel', 'Rodriguez', '1987-04-18', 'http://www.danielrodriguezactor.com', 'Daniel Rodriguez is known for his powerful performances in dramatic films.'),
('Olivia', 'Martinez', '1991-08-30', 'http://www.oliviamartinezactress.com', 'Olivia Martinez is an actress with a passion for indie films and character-driven stories.'),
('James', 'Lee', '1981-12-05', 'http://www.jamesleeactor.com', 'James Lee has a background in comedy and has appeared in several hit sitcoms.'),
('Isabella', 'Clark', '1988-02-17', 'http://www.isabellaclarkactress.com', 'Isabella Clark is a well-known actress in the science fiction genre.'),
('Ethan', 'Harris', '1986-11-10', 'http://www.ethanharrisactor.com', 'Ethan Harris is a character actor with a wide range of roles in both film and television.'),
('Mia', 'Lewis', '1993-03-27', 'http://www.mialewisactress.com', 'Mia Lewis is a fresh face in the industry, making her mark in both drama and thriller genres.'),
('Alexander', 'Walker', '1982-05-14', 'http://www.alexanderwalkeractor.com', 'Alexander Walker is an accomplished actor known for his work in historical dramas.'),
('Lily', 'Hall', '1990-07-29', 'http://www.lilyhallactress.com', 'Lily Hall has appeared in several popular television series and is known for her comedic timing.'),
('Noah', 'Young', '1989-10-22', 'http://www.noahyoungactor.com', 'Noah Young is a talented actor who has played leading roles in numerous action films.'),
('Grace', 'King', '1984-12-09', 'http://www.gracekingactress.com', 'Grace King is an actress known for her strong performances in both film and television.'),
('Lucas', 'Wright', '1995-06-08', 'http://www.lucaswrightactor.com', 'Lucas Wright is an emerging star in the action and adventure genres.'),
('Charlotte', 'Hill', '1992-09-15', 'http://www.charlottehillactress.com', 'Charlotte Hill is a rising talent with roles in both indie films and major studio productions.'),
('Henry', 'Scott', '1978-11-25', 'http://www.henryscottactor.com', 'Henry Scott is a veteran actor known for his work in both drama and thriller films.'),
('Ava', 'Green', '1987-01-03', 'http://www.avagreenactress.com', 'Ava Green is a dynamic actress with a background in theater and film.'),
('Elijah', 'Rivera', '1983-07-12', 'http://www.elijahriveraactor.com', 'Elijah Rivera has appeared in numerous science fiction films and is known for his versatility.'),
('Sophia', 'Baker', '1994-04-21', 'http://www.sophiabakeractress.com', 'Sophia Baker is a young actress with a growing portfolio of diverse roles in film.'),
('Liam', 'Nelson', '1981-06-30', 'http://www.liamnelsonactor.com', 'Liam Nelson is a seasoned actor known for his roles in psychological thrillers.'),
('Harper', 'Carter', '1990-02-16', 'http://www.harpercarteractress.com', 'Harper Carter is an actress recognized for her powerful performances in drama films.'),
('Benjamin', 'Collins', '1975-10-03', 'http://www.benjamincollinsactor.com', 'Benjamin Collins is a veteran actor with a career spanning over two decades.'),
('Ella', 'Morgan', '1988-08-19', 'http://www.ellamorganactress.com', 'Ella Morgan is known for her work in romantic comedies and light-hearted films.'),
('Jackson', 'Brooks', '1985-05-23', 'http://www.jacksonbrooksactor.com', 'Jackson Brooks is a character actor known for his roles in suspense and thriller films.'),
('Lily', 'Turner', '1991-11-05', 'http://www.lilyturneractress.com', 'Lily Turner has appeared in both mainstream and indie films, showcasing her versatility.'),
('Samuel', 'Morris', '1983-02-24', 'http://www.samuelmorrisactor.com', 'Samuel Morris is an actor who has made a name for himself in crime and mystery films.'),
('Amelia', 'Perez', '1990-03-11', 'http://www.ameliaperezactress.com', 'Amelia Perez is an up-and-coming actress with a passion for intense drama roles.'),
('Oliver', 'Edwards', '1987-12-20', 'http://www.oliveredwardsactor.com', 'Oliver Edwards is a dynamic actor known for his performances in both drama and action films.'),
('Sofia', 'Hughes', '1993-01-16', 'http://www.sofiahughesactress.com', 'Sofia Hughes has appeared in numerous films and television series, gaining critical acclaim.'),
('Jacob', 'Reed', '1980-09-04', 'http://www.jacobreedactor.com', 'Jacob Reed is a seasoned actor known for his roles in historical and biographical films.'),
('Isabella', 'Russell', '1995-06-27', 'http://www.isabellarussellactress.com', 'Isabella Russell is a young actress who has quickly risen to fame through her powerful performances.'),
('Ethan', 'Barnes', '1992-10-31', 'http://www.ethanbarnesactor.com', 'Ethan Barnes is known for his intense performances in both action and drama films.'),
('Charlotte', 'Ross', '1985-11-18', 'http://www.charlotterossactress.com', 'Charlotte Ross has appeared in numerous indie films and is known for her nuanced performances.'),
('James', 'Henderson', '1989-07-03', 'http://www.jameshendersonactor.com', 'James Henderson is an actor with a broad range of roles in both film and television.'),
('Grace', 'Cole', '1990-08-09', 'http://www.gracecoleactress.com', 'Grace Cole is a versatile actress known for her work in both period dramas and modern thrillers.'),
('Daniel', 'Morgan', '1984-05-15', 'http://www.danielmorganactor.com', 'Daniel Morgan is a well-known actor who has appeared in several critically acclaimed films.');


-- Movies
INSERT INTO Movies (title, release_year, duration_minutes, rating, overview, director_id, genre_id) VALUES
('Inception', 2010, 148, 8.8, 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('The Godfather', 1972, 175, 9.2, 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('The Dark Knight', 2008, 152, 9.0, 'When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('Pulp Fiction', 1994, 154, 8.9, 'The lives of two mob hitmen, a boxer, a gangster, and his wife intertwine in four tales of violence and redemption.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('Schindlers List', 1993, 195, 8.9, 'In German-occupied Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('Fight Club', 1999, 139, 8.8, 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('Forrest Gump', 1994, 142, 8.8, 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal, and other historical events unfold through the perspective of an Alabama man with an IQ of 75.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('The Matrix', 1999, 136, 8.7, 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('The Lord of the Rings: The Return of the King', 2003, 201, 8.9, 'Gandalf and Aragorn lead the World of Men against Saurons army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('The Silence of the Lambs', 1991, 118, 8.6, 'A young FBI cadet must confide in an incarcerated and manipulative killer to receive his help on catching another serial killer.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('Interstellar', 2014, 169, 8.6, 'A team of explorers travel through a wormhole in space in an attempt to ensure humanitys survival.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('Gladiator', 2000, 155, 8.5, 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('The Prestige', 2006, 130, 8.5, 'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('The Lion King', 1994, 88, 8.5, 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('Memento', 2000, 113, 8.4, 'A man with short-term memory loss attempts to track down his wifes murderer.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('The Departed', 2006, 151, 8.5, 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('Whiplash', 2014, 106, 8.5, 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student\'s potential.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('Parasite', 2019, 132, 8.6, 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('The Green Mile', 1999, 189, 8.6, 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('Inglourious Basterds', 2009, 153, 8.3, 'In Nazi-occupied France, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner\'s vengeful plans for the same.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('The Shawshank Redemption', 1994, 142, 9.3, 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('The Avengers', 2012, 143, 8.0, 'Earths mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('Jurassic Park', 1993, 127, 8.2, 'During a preview tour, a theme park suffers a major power breakdown that allows its cloned dinosaur exhibits to run amok.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('Titanic', 1997, 195, 7.8, 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('The Wolf of Wall Street', 2013, 180, 8.2, 'Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption, and the federal government.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('Mad Max: Fury Road', 2015, 120, 8.1, 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('Braveheart', 1995, 178, 8.3, 'Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('Avatar', 2009, 162, 7.8, 'A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('Saving Private Ryan', 1998, 169, 8.6, 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('The Social Network', 2010, 120, 7.7, 'Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, but is later sued by two brothers who claimed he stole their idea.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('Django Unchained', 2012, 165, 8.4, 'With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation-owner in Mississippi.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('The Big Lebowski', 1998, 117, 8.1, 'Jeff "The Dude" Lebowski, mistaken for a millionaire of the same name, seeks restitution for his ruined rug and enlists his bowling buddies to help get it.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('The Shining', 1980, 146, 8.4, 'A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('A Beautiful Mind', 2001, 135, 8.2, 'After John Nash, a brilliant but asocial mathematician, accepts secret work in cryptography, his life takes a turn for the nightmarish.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('The Pianist', 2002, 150, 8.5, 'A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('Goodfellas', 1990, 146, 8.7, 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('Slumdog Millionaire', 2008, 120, 8.0, 'A Mumbai teenager reflects on his life after being accused of cheating on the Indian version of "Who Wants to Be a Millionaire?".', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('Black Panther', 2018, 134, 7.3, 'TChalla, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country\'s past.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('La La Land', 2016, 128, 8.0, 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('The Grand Budapest Hotel', 2014, 99, 8.1, 'A writer encounters the owner of an aging high-class hotel and recounts his story of working as a lobby boy in the hotels glorious years under an exceptional concierge.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7))),
('Guardians of the Galaxy', 2014, 121, 8.0, 'A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.', FLOOR(1 + (RAND() * 50)), FLOOR(1 + (RAND() * 7)));

-- Continue with additional insert statements to complete 200 rows.



-- Insert Movie-Actor relations
INSERT INTO MovieActors (movie_id, actor_id) VALUES
(1,1),
(2,2),
(3,3),
(4,4),
(5,5),
(6,6),
(7,7),
(8,8),
(9,9),
(10,10),
(11,11),
(12,12),
(13,13),
(14,14),
(15,15),
(16,16),
(17,17),
(18,18),
(19,19),
(20,20),
(21,21),
(22,22),
(23,23),
(24,24),
(25,25),
(26,26),
(27,27),
(28,28),
(29,29),
(30,30),
(31,31),
(1,25),
(2,24),
(3,23),
(4,22),
(5,21),
(6,20),
(7,19),
(8,18),
(9,17),
(10,16),
(11,15),
(12,14),
(14,12),
(15,11),
(16,10),
(17,9),
(18,8),
(19,7),
(20,6),
(21,5),
(22,4),
(23,3),
(24,2),
(25,1),
(26,0),
(27,26),
(28,27),
(29,28),
(30,29),
(31,30)


-- Insert Movie-Actor relations
INSERT INTO MovieWritters (movie_id, writter_id) VALUES
(1,1),
(2,2),
(3,3),
(4,4),
(5,5),
(6,6),
(7,7),
(8,8),
(9,9),
(10,10),
(11,11),
(12,12),
(13,13),
(14,14),
(15,15),
(16,16),
(17,17),
(18,18),
(19,19),
(20,20),
(21,21),
(22,22),
(23,23),
(24,24),
(25,25),
(26,26),
(27,27),
(28,28),
(29,29),
(30,30),
(31,31),
(1,25),
(2,24),
(3,23),
(4,22),
(5,21),
(6,20),
(7,19),
(8,18),
(9,17),
(10,16),
(11,15),
(12,14),
(14,12),
(15,11),
(16,10),
(17,9),
(18,8),
(19,7),
(20,6),
(21,5),
(22,4),
(23,3),
(24,2),
(25,1),
(26,0),
(27,26),
(28,27),
(29,28),
(30,29),
(31,30)

INSERT INTO Users (username, email, password) VALUES
('john_doe', 'john.doe@example.com', '$2y$10$KqUQ3bTjLBONExY4E/WIeOXP3OmhyNhQ8tQZaU2FeJzyYhBzW1.a2'),
('emily_smith', 'emily.smith@example.com', '$2y$10$gMO6GBYYRC5wseJn9h6/Z.lB/QJ2bPEZ/hTkwmG4.hSGqOVdSbgBa'),
('michael_johnson', 'michael.johnson@example.com', '$2y$10$Ox.j3Q1mUesVRmRBmOeyuOd8RXrryG94X62Q/yxsXTN/eSwJKb4m6'),
('sarah_williams', 'sarah.williams@example.com', '$2y$10$tg8F/JjfGmIhYeZBoMihnOeyzI0sps/7g8HFhMHuRPFnU7xnCjPne'),
('david_brown', 'david.brown@example.com', '$2y$10$uEt/8WxPfH8GSD.4ebIxXOZmsDd0fiZMA7RQ9FdSKAomFlPZT7jMy'),
('sophia_garcia', 'sophia.garcia@example.com', '$2y$10$JypdMA62B2XkdsmvSKn0fOHFrbmIPrFO70jB9EESqMIxl6vAolomK'),
('daniel_rodriguez', 'daniel.rodriguez@example.com', '$2y$10$MXOyb5LjNTTkgqXqwhvjMej0ImICi3/TBG4M7sPZ2bHlY/GT2SwOC'),
('olivia_martinez', 'olivia.martinez@example.com', '$2y$10$DhN/qD9Qu/TNlgNya9NGuulSi5pGgmxeIYXn7mYzxOSpjzpsWZ2Bq'),
('james_lee', 'james.lee@example.com', '$2y$10$PtNBZk/hyHzrHc3Rlb0x.eK1cvts5gKAYrkUtH6.O4VbsVKoKcvS6'),
('isabella_clark', 'isabella.clark@example.com', '$2y$10$JqsHlmNTTzV9x0vE2VRhCuM1ZpUVUIZJ82Y5XhXMiNhmCT9OcBuDW'),
('ethan_harris', 'ethan.harris@example.com', '$2y$10$eFmOZmRhZPHI4dNDJXYhFu/ZJefFVxxNWRrxjz7gWZzJrSRbypA12'),
('mia_lewis', 'mia.lewis@example.com', '$2y$10$A9McBGoyus0ZtBHTG9U2ueO/N4/N5zfrAcF9DJbNeB25SuJdHDmuO'),
('alexander_walker', 'alexander.walker@example.com', '$2y$10$8t/7WRw.lV1SHXkeNdTRbOnTAw0I1GP6nX3Pml3akxxGcVKR.XuMi'),
('lily_hall', 'lily.hall@example.com', '$2y$10$yqiBPJZcKOxBYQnWjRtmk.Gy73jUh5FyWqFtMRYJFrj9/Gzzos1wW'),
('noah_young', 'noah.young@example.com', '$2y$10$d3/xGDwFOwAFbbEGUB9QSe5XTZzMQnxrAT6pG74ClhfPVFuYPtI8i'),
('grace_king', 'grace.king@example.com', '$2y$10$HlrxsXG8rjZlA0Qnht3V/.4BCTa3JrCoq.fKakVk8yZMKndz0BbJW'),
('lucas_wright', 'lucas.wright@example.com', '$2y$10$HtYFy4Bf6md2OPu9Z/SvBOvUu0wbSeCzTPxAcNjgEV8OFKPeuPv.m'),
('charlotte_hill', 'charlotte.hill@example.com', '$2y$10$SBLZfGeBMK0bcX2c53AB5OjsJ2NjCJvAXA/FlbhJ6fOoH8RW34ZBm'),
('henry_scott', 'henry.scott@example.com', '$2y$10$rG.q.mSbVYfdZx78ev8.mOZfwxYPpe3GsqnC82/GuW.Kf/NVXE9mO'),
('ava_green', 'ava.green@example.com', '$2y$10$9zNyd6PfVpTH5Ov6qDjKuOhAdCoQZlHdWWzwLKwF5Yej4VGviKgaq'),
('elijah_rivera', 'elijah.rivera@example.com', '$2y$10$7K5fSZlTlWMOu/o5OXcyx.uLJ/m7GVrLTPbwRYHhXhZwYXmOnxuZy'),
('sophia_baker', 'sophia.baker@example.com', '$2y$10$ewiUnKwiuwLO.BkSnz6RIu/O1ytMBwQuHwKJ4s3F8mloS4lICuO4e'),
('liam_nelson', 'liam.nelson@example.com', '$2y$10$9MyoQ10Lz3lK93UbAYRP/uY9pySR51UGQ7xyHlTPyFHHyyHpgnL2m'),
('harper_carter', 'harper.carter@example.com', '$2y$10$9uOhb2kJ07yQ19SBFzoOZO2S9jO2NW/gJQWYoxu78MgBFdBWcJ2u6'),
('benjamin_collins', 'benjamin.collins@example.com', '$2y$10$CwTUMyT5CeMDoplvHcY4guN5N1Yy7w99Qy4sLcnfJNRJPqLT8uoNu'),
('ella_morgan', 'ella.morgan@example.com', '$2y$10$aOSGnl6eGt5NVr4xyNXACuT0fBgzLl0P2hlA62NPxe1dNVx.oD36S'),
('jackson_brooks', 'jackson.brooks@example.com', '$2y$10$w6ZymDCPkZQ/c5wY7xYl7eJCRu1nIlKl67H9hU/0zSPuE9EkqYZlS'),
('lily_turner', 'lily.turner@example.com', '$2y$10$cf0zXtRJryCE2hLK1DlN/eM4bUgN.yCLvLVmSBFLsmYrYO54HKHO6'),
('samuel_morris', 'samuel.morris@example.com', '$2y$10$5dy5fx4i8/5nxGjO/LD89OBNaRcRsqz4MCqjfHe4Ip84G/hOYO/jS'),
('amelia_perez', 'amelia.perez@example.com', '$2y$10$ljJJNVv/Dp5qlmpOiWRLpuXUbf4M5Dz7g3F.VtVtX2HYGf.ny.sgu'),
('oliver_edwards', 'oliver.edwards@example.com', '$2y$10$5HDf9ovSyeT5ImXeKJjABOJZltQCUfKvFCmVG2dsYg8exMEVb3FX6'),
('sofia_hughes', 'sofia.hughes@example.com', '$2y$10$YPqKuOTI5u9aGV15Oo6Ap.yLCT8iVhsEyqOc7N6bxPToM8X8vlWWm'),
('jacob_reed', 'jacob.reed@example.com', '$2y$10$4kBcOcKsvsUl/nV1F7dW2OSqiEuEbndgFMlGdxybCVErkN9nQqRNG'),
('isabella_russell', 'isabella.russell@example.com', '$2y$10$OXpOjvg.WQaCfK72rUBOBugM/WQz.QAkxBWFS9InGIgmQNdtnW8ne'),
('ethan_barnes', 'ethan.barnes@example.com', '$2y$10$xDLNlcfExfRleFz67xVuqOxtuME4czTGRRWvIbKFuGGnLVhDJyP.G'),
('charlotte_ross', 'charlotte.ross@example.com', '$2y$10$tj9YpzuVle5uMXpgI8j0ouUwTX8GSaT8vstxOUJNPZo1RGcRhYVly'),
('james_henderson', 'james.henderson@example.com', '$2y$10$3vWUvWR6XzAvm.pSKppLsOVIvFSTQvJWuvBPrvCVTWeFD2CQGDO.e'),
('grace_cole', 'grace.cole@example.com', '$2y$10$x7nKPeJyxFObFkP2SrwNheMWLLYr.CGMCe7GpUdrOJXEv6Wo1tOHC'),
('daniel_morgan', 'daniel.morgan@example.com', '$2y$10$CQDQF1osSW03Z7Hp6TiQ3ewem1.Rk7e.xmQY/EfXKDZ3QXJbA6tuq'),
('mia_bennett', 'mia.bennett@example.com', '$2y$10$dMygR1KugzfqUolxy5KmseCVmLQWhuLQrlWz6yDe9hVkcw5eMtyYK'),
('jackson_wright', 'jackson.wright@example.com', '$2y$10$pKzpTwse5owqJmgOs/Z56Oi5pFZGbdNTZWyXItGHDWvUb9/NbRJZK'),
('ava_richards', 'ava.richards@example.com', '$2y$10$W/RW1k5HDvDlxdGzAOn30uG0VSUvxzTy.x28yxRDhEAgBdKJeKseK'),
('oliver_evans', 'oliver.evans@example.com', '$2y$10$fbQkN0wov0M7sNPs6fYXvOxiZ/Ps6MP4HOAygMNLlWDv79BXcFXcy'),
('lily_ross', 'lily.ross@example.com', '$2y$10$ypjj9OHG8L6XQXqVV5Jc.Ogf9YybYXol2uS8wYvBWkwmrY7QhUP32'),
('liam_hall', 'liam.hall@example.com', '$2y$10$WyogCeCsixEcbnhLtiF62uVnJsQPCbbqD9wnP9YgDYhxV0/6Ym54S'),
('grace_bailey', 'grace.bailey@example.com', '$2y$10$byX1yfh6OzzlBKH5RtFLROQvcLVuAmPY0nOYbYf0vB8YfNzMJjBmS'),
('lucas_turner', 'lucas.turner@example.com', '$2y$10$odKZZ5Y2QXXfA/D3sOi1Bupx65fFkIqAlyJhu5TcBtzeU6zUaj9F2');


INSERT INTO UserPreferenceActors( user_id, actor_id) VALUES 
(1,25),
(2,24),
(3,23),
(4,22),
(5,21),
(6,20),
(7,19),
(8,18),
(9,17),
(10,16),
(11,15),
(12,14),
(13,13),
(14,12),
(15,11),
(16,10),
(17,9),
(18,8),
(19,7),
(20,6),
(1,1),
(2,2),
(3,3),
(4,4),
(5,5),
(6,6),
(7,7),
(8,8),
(9,9),
(10,10),
(11,11),
(12,12),
(14,14),
(15,15),
(16,16),
(17,17),
(18,18),
(19,19),
(20,20),
(21,21),
(22,22),
(23,23),
(24,24),
(25,25),
(26,26),
(27,27),
(28,28),
(29,29),
(30,30),
(31,31)


INSERT INTO UserPreferenceWritters( user_id, writter_id) VALUES 
(1,25),
(2,24),
(3,23),
(4,22),
(5,21),
(6,20),
(7,19),
(8,18),
(9,17),
(10,16),
(11,15),
(12,14),
(13,13),
(14,12),
(15,11),
(16,10),
(17,9),
(18,8),
(19,7),
(20,6),
(1,1),
(2,2),
(3,3),
(4,4),
(5,5),
(6,6),
(7,7),
(8,8),
(9,9),
(10,10),
(11,11),
(12,12),
(14,14),
(15,15),
(16,16),
(17,17),
(18,18),
(19,19),
(20,20),
(21,21),
(22,22),
(23,23),
(24,24),
(25,25),
(26,26),
(27,27),
(28,28),
(29,29),
(30,30),
(31,31)


INSERT INTO UserPreferenceGenre( user_id, genre_id) VALUES 
(1,25),
(2,24),
(3,23),
(4,22),
(5,21),
(6,20),
(7,19),
(8,18),
(9,17),
(10,16),
(11,15),
(12,14),
(13,13),
(14,12),
(15,11),
(16,10),
(17,9),
(18,8),
(19,7),
(20,6),
(1,1),
(2,2),
(3,3),
(4,4),
(5,5),
(6,6),
(7,7),
(8,8),
(9,9),
(10,10),
(11,11),
(12,12),
(14,14),
(15,15),
(16,16),
(17,17),
(18,18),
(19,19),
(20,20),
(21,21),
(22,22),
(23,23),
(24,24),
(25,25),
(26,26),
(27,27),
(28,28),
(29,29),
(30,30),
(31,31)